name: deploy-profile

on:
  push:
    branches:
      - master
    paths:
      - 'profile/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: cd profile  && docker build -t abinv/profile -f Dockerfile.prod .
      - run: docker push abinv/profile
      #  # Commenting out Digital Ocean specific steps since we're not deploying there now
      # - uses: digitalocean/action-doctl@v2
      #   with:
      #     token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      # - run: doctl kubernetes cluster kubeconfig save devhive-hosted-clusterr
      # - run: kubectl rollout restart deployment profile-depl